# -*- coding: utf-8 -*-
"""Angela Yu 100 days of code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ieG0XC1xGod5R1D8vQnzKWBJbdPVa2S5
"""

#100 days of python challenge 
#pizza order calculator
# 🚨 Don't change the code below 👇
print("Welcome to Python Pizza Deliveries!")
size = input("What size pizza do you want? S, M, or L ")
add_pepperoni = input("Do you want pepperoni? Y or N ")
extra_cheese = input("Do you want extra cheese? Y or N ")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
total=0
if size =="S":
    total += 15

elif size == 'M':
    total += 20

else:
    total += 25

if add_pepperoni == "Y":
    if size =="S":
        total += 2
    else:
        total += 3

if extra_cheese =="Y":
    total += 1


print('Your final bill is: $'+str(total))


#love calculator
#For this exercise, we use the input function, if statement and concatenate
# 🚨 Don't change the code below 👇
print("Welcome to the Love Calculator!")
name1 = input("What is your name? \n")
name2 = input("What is their name? \n")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
combined= name1 + name2
total=combined.lower()

t = total.count ("t")
r = total.count ("r")
u = total.count ("u")
e = total.count ("e")
true=t + r + u + e
l = total.count ("l")
o = total.count ("o")
v = total.count ("v")
e = total.count ("e")
love=l + o + v + e   

true_love=str(true)+str(love)

total_score=int(true_love)

if (total_score < 10) or (total_score > 90):
    print (f"Your score is {true_love}, you go together like coke and mentos.")
elif (total_score > 39) and (total_score < 51):
    print (f"Your score is {true_love}, you are alright together.")
else:
    print(f"Your score is {true_love}.")



#coin toss
#Remember to use the random module
#Hint: Remember to import the random module here at the top of the file. 🎲
	 
# 🚨 Don't change the code below 👇
test_seed = int(input("Create a seed number: "))
 # 🚨 Don't change the code above 👆 It's only for testing your code.
	 
#Write the rest of your code below this line 👇
import random
random_toss = random.randint(0, 1)
if random_toss == 1:
    print ('Heads')
else:
     print ('Tails')

#treasure island game


print ('Welcome to Treasure island!')
print ('Your mission is to find the treasure.')
question_1 = input("There is two door, A blue door and a red door, which way do you want to go?").lower
if question_1= 'red door'
  print ('You got lucky, You may proceed in the game.')
  question_2=input("There is two door, door 1 - 2 , which way do you want to go?").lower
  if question_2 ='door 1'
    print ('That'/s a dead end, Game over.')
    else if question_2 ='door 1'
    print ('Here is the treasure. Congratulations, You won.')
elif question_1 ='blue door'
    print ('That'/s a dead end, Game over.')
else
  print ('I didn'/t understand that, Game over.')

print ('Welcome to Treasure island!\nYour mission is to find the treasure.')

"""Retry on another way """

#treasure island game
print ('Welcome to Treasure island!')
print ('Your mission is to find the treasure.')
question_1 = input("There is two door, A blue door and a red door, which way do you want to go?").lower()
if question_1== 'red door':
  print ('You got lucky. You may proceed in the game.')
  question_2 = input("There is two door, door 1 - 2 , which way do you want to go?").lower
  if question_2 =='door 1':
    print ('That\'s a dead end, Game over.')
  else:
    print ('Here is the treasure. Congratulations! You won.')
else:
    print ('That\'s a dead end, Game over.')

#nested list
fruits = ["Strawberries", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears"]
vegetables = ["Spinach", "Kale", "Tomatoes", "Celery", "Potatoes"]
     
dirty_dozen = [fruits, vegetables]
     
print(dirty_dozen[1][1])

#nested list
fruits = ["Strawberries", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears"]
vegetables = ["Spinach", "Kale", "Tomatoes", "Celery", "Potatoes"]
     
dirty_dozen = [fruits, vegetables]
print(dirty_dozen[0])
# this script print the list found in fruits list

#nested list
fruits = ["Strawberries", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears"]
vegetables = ["Spinach", "Kale", "Tomatoes", "Celery", "Potatoes"]
     
dirty_dozen = [fruits, vegetables]
print(dirty_dozen[1])
#this script print the list found in vegetable list

#nested list
fruits = ["Strawberries", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears"]
vegetables = ["Spinach", "Kale", "Tomatoes", "Celery", "Potatoes"]
     
dirty_dozen = [fruits, vegetables]

print(dirty_dozen[1][2])
#for this part, list 1 will be vegetable and list 2 will be tomatoes(counting started at 0 same with the first number)

#nested list
fruits = ["Strawberries", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears"]
vegetables = ["Spinach", "Kale", "Tomatoes", "Celery", "Potatoes"]
     
dirty_dozen = [fruits, vegetables]
print(dirty_dozen[1][3])
#for this part, list 1 will be vegetable and list 3 will be celery(counting started at 0 same with the first number)

user_choice=int(input("What do you choose? Type 0 for Scissors, 1 for Paper or 2 for Rock.\n"))
scissors =("""
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
""")



paper=("""
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
""")

rock = ('''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
''')


hand=[scissors,paper,rock]

import random
random_hand=[scissors,paper,rock]
computer_choice=int((random.randint(0, 2)))
#lets define the computer choice
if computer_choice == 0 :
  print('Computer chose:]}.') 
  print(hand[0]) 
elif computer_choice ==1:
  print('Computer chose:') 
  print(hand[1])  
else:
  print('Computer chose:')
  print(hand[2]) 

if user_choice >= 3 or user_choice < 0:
  print ("I didn't understand that, You lose!")  
else:  
  print("You chose: ")    
  print(hand[user_choice])  

##print ("computer_choice is" + " "+ str(computer_choice))
##print ("user_choice is" + " "+ str(user_choice))
#lets declare the winner
if user_choice == computer_choice:
  print ("Its a tie.")
elif user_choice==0 and computer_choice==2:
  print ("You lose!")    
elif user_choice==2 and computer_choice==0:
  print ("You win!")      
elif user_choice >= 3:
  print ("I didn't understand that, You lose!")  
elif user_choice > computer_choice:
  print ("You won!")
elif user_choice < computer_choice:
  print ("You lose!")
else:
  print ("You lose")

hand=['Scissors','Paper','Rock']
import random
number=int(input('Pick a number(0-2)'))
computer_choice=int((random.randint(0, 2)))
print (f'Computer chose {computer_choice}.')
print (f'You chose {number}')



import random
scissors =("""
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
""")



paper=("""
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
""")

rock = ('''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
''')
hand=[scissors,paper,rock]
user_choice=int(random.randint(0,2))
print(hand[user_choice])

fruits= ["Apple","Pie","Mango","Pineapple"]
for fruit in fruits:
  print(fruit)
  print(fruit+ ' '+ 'pie')

"""Practice for statement-this is the example in the course"""

Vegetables= ["Carrot","Potato","Monggo","Sayote"]
for fruit in Vegetables:
  print(fruit)
  print(fruit+ ' '+ 'silog')

"""For loop exercise-corey """

x=1
while x< 100:
        break
        print (x)
        x += 1

# 🚨 Don't change the code below 👇
student_heights = input("Input a list of student heights ").split()
for n in range(0, len(student_heights)):
  student_heights[n] = int(student_heights[n])
# print(student_heights)
# 🚨 Don't change the code above 👆

#Write your code below this row 👇

total_height = 0
for height in student_heights:
  total_height += height
print(f"total height = {total_height}")

number_of_students = 0
for student in student_heights:
  number_of_students += 1
print(f"number of students = {number_of_students}")
  
average_height = round(total_height / number_of_students)
print(average_height)









































#Write your code above this line 👆
# 🚨 Do NOT modify the code below this line 👇

with open('testing_copy.py', 'w') as file:
  file.write('def test_func():\n')
  with open('main.py', 'r') as original:
    f2 = original.readlines()[0:40]
    for x in f2:
      file.write("    " + x)

import testing_copy
import unittest
from unittest.mock import patch
from io import StringIO
import os

class MyTest(unittest.TestCase):
  def run_test(self, given_answer, expected_print): 
    with patch('builtins.input', return_value=given_answer), patch('sys.stdout', new=StringIO()) as fake_out: 
      testing_copy.test_func()
      self.assertEqual(fake_out.getvalue(), expected_print) 

  def test_1(self):
    self.run_test(given_answer='180 124 165 173 189 169 146', expected_print='total height = 1146\nnumber of students = 7\n164\n')
  
  def test_2(self):
    self.run_test(given_answer='150 142 185 120 171 184 149 199', expected_print='total height = 1300\nnumber of students = 8\n162\n')


print("\n\n\n.\n.\n.")
print('Checking that the code prints the average height (and other print statements above) rounded to the nearest integer for several different lists of heights.\n')
print('\nRunning some tests on your code:')
print(".\n.\n.")
unittest.main(verbosity=1, exit=False)

os.remove("testing_copy.py")

# 🚨 Don't change the code below 👇
student_heights = input("Input a list of student heights ").split()
for n in range(0, len(student_heights)):
  student_heights[n] = int(student_heights[n])
print(student_heights)
# 🚨 Don't change the code above 👆

#Write your code below this row 👇
#use for loop in computing total height
total_height=0
for height in student_heights:
  total_height += height
print (total_height)

# use for loop in computing number of students
number_of_students = 0

for student in student_heights:
  number_of_students += 1
print (number_of_students)

average=round(total_height/number_of_students)
print (average)

# 🚨 Don't change the code below 👇
student_scores = input("Input a list of student scores ").split()
for n in range(0, len(student_scores)):
  student_scores[n] = int(student_scores[n])
print(student_scores)
# 🚨 Don't change the code above 👆

#Write your code below this row 👇
x= 0
for n in student_scores:
  if n > x:
    x = n
print (x)

#for loop
total = 0
for number in range(1,101):
  total += number
print (total)

total = 0
for number in range(2,101,2):
  total += number
print (total)

total = 0
for number in range(1,101):
  if number % 2 == 0:
    total += number
print (total)

"""You are going to write a program that automatically prints the solution to the FizzBuzz game.

    Your program should print each number from 1 to 100 in turn.

    When the number is divisible by 3 then instead of printing the number it should print "Fizz".

    When the number is divisible by 5, then instead of printing the number it should print "Buzz".`

      And if the number is divisible by both 3 and 5 e.g. 15 then instead of the number it should print "FizzBuzz"

e.g. it might start off like this:
"""

#name the variable
for n in range (1,101):
  if n % 3 == 0 and n % 5 == 0:
     print ("FizzBuzz") 
  elif n % 3== 0:
      print("Fizz")
  elif n % 5== 0:
      print ("Buzz")    
     
  else:
      print (n)

#Password Generator Project
import random
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the PyPassword Generator!")
nr_letters= int(input("How many letters would you like in your password?\n"))
nr_symbols=int(input(f"How many symbols would you like?\n") )
nr_numbers= int(input(f"How many numbers would you like?\n"))
password=""
for n in range (1,nr_letters+1):
    random_char=random.choice(letters)
    password += random_char

for n in range (1,nr_symbols+1):
    random_char2=random.choice(symbols)
    password += random_char2

for n in range (1,nr_numbers+1):
    random_char3=random.choice(numbers)
    password += random_char3
print(password)

#Password Generator Project
import random
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the PyPassword Generator!")
nr_letters= int(input("How many letters would you like in your password?\n"))
nr_symbols=int(input(f"How many symbols would you like?\n") )
nr_numbers= int(input(f"How many numbers would you like?\n"))
password=""
for n in range (1,nr_letters+1):
    password += random.choice(letters)

for n in range (1,nr_symbols+1):
    password += random.choice(symbols)

for n in range (1,nr_numbers+1):
    password += random.choice(numbers)
print(password)



#Password Generator Project
import random
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the PyPassword Generator!")
nr_letters= int(input("How many letters would you like in your password?\n"))
nr_symbols=int(input(f"How many symbols would you like?\n") )
nr_numbers= int(input(f"How many numbers would you like?\n"))
password_list=[]
for n in range (1,nr_letters+1):
    password_list += random.choice(letters)

for n in range (1,nr_symbols+1):
    password_list += random.choice(symbols)

for n in range (1,nr_numbers+1):
    password_list += random.choice(numbers)
#we can use append
# password_list.append(random.choice(numbers))
print(password_list)
random.shuffle(password_list)
print(password_list)
password =""
for x in password_list:
  password += x
print(password)
print (f"Your Password is: {password}")