# -*- coding: utf-8 -*-
"""Angela Yu 100 days of code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ieG0XC1xGod5R1D8vQnzKWBJbdPVa2S5
"""

#100 days of python challenge 
#pizza order calculator
# 🚨 Don't change the code below 👇
print("Welcome to Python Pizza Deliveries!")
size = input("What size pizza do you want? S, M, or L ")
add_pepperoni = input("Do you want pepperoni? Y or N ")
extra_cheese = input("Do you want extra cheese? Y or N ")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
total=0
if size =="S":
    total += 15

elif size == 'M':
    total += 20

else:
    total += 25

if add_pepperoni == "Y":
    if size =="S":
        total += 2
    else:
        total += 3

if extra_cheese =="Y":
    total += 1


print('Your final bill is: $'+str(total))


#love calculator
#For this exercise, we use the input function, if statement and concatenate
# 🚨 Don't change the code below 👇
print("Welcome to the Love Calculator!")
name1 = input("What is your name? \n")
name2 = input("What is their name? \n")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
combined= name1 + name2
total=combined.lower()

t = total.count ("t")
r = total.count ("r")
u = total.count ("u")
e = total.count ("e")
true=t + r + u + e
l = total.count ("l")
o = total.count ("o")
v = total.count ("v")
e = total.count ("e")
love=l + o + v + e   

true_love=str(true)+str(love)

total_score=int(true_love)

if (total_score < 10) or (total_score > 90):
    print (f"Your score is {true_love}, you go together like coke and mentos.")
elif (total_score > 39) and (total_score < 51):
    print (f"Your score is {true_love}, you are alright together.")
else:
    print(f"Your score is {true_love}.")



#coin toss
#Remember to use the random module
#Hint: Remember to import the random module here at the top of the file. 🎲
	 
# 🚨 Don't change the code below 👇
test_seed = int(input("Create a seed number: "))
 # 🚨 Don't change the code above 👆 It's only for testing your code.
	 
#Write the rest of your code below this line 👇
import random
random_toss = random.randint(0, 1)
if random_toss == 1:
    print ('Heads')
else:
     print ('Tails')